---
#
# Ansible managed
#
repository:
  description: Node.js installation for Linux
  homepage: https://buluma.github.io/
  topics: development, web, javascript, js, node, npm, nodejs, ansible, molecule, tox, playbook
