---
image: "buluma/github-action-molecule:4.0.9"

variables:
  PY_COLORS: 1

molecule:
  stage: build
  allow_failure: false
  script:
    - image=${image} tag=${tag} molecule test
  retry: 0
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "7"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "debian-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"

testing:
  stage: test
  allow_failure: true
  needs: []
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  retry: 1
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "7"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "debian-systemd"
        tag: "latest"
      - image: "debian-systemd"
        tag: "buster"
      - image: "docker-ubuntu-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"
      - image: "docker-ubuntu-systemd"
        tag: "jammy"
